### ISSUE TITLE
Where can we download SimpleCap 1.2?

### ISSUE THREAD

**Issue by kenjis** [xcatsan/SimpleCap-1.2#1]
Thank you for releasing the nice application like this.

It seems the official download site was closed. So we can't download it now.
Would you please give me a new official download URL?

**Comment by xcatsan** [comment]
Thank you for your mail.
I fixed homepage trouble (the domain has been expired…）.
You can download SimpleCap now.

http://xcatsan.com/simplecap-en/ http://xcatsan.com/simplecap-en/

Many thanks,
Hiroshi Hashiguchi

**Comment by kenjis** [comment]
Thank you for your quick response!
